FROM node:22-alpine

ENV TZ=America/Sao_Paulo
WORKDIR /usr/app

RUN apk add --no-cache \
  python3 \
  make \
  g++ \
  bash \
  libc6-compat

RUN corepack enable && corepack prepare yarn@1.22.22 --activate

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . .

EXPOSE 5501

CMD ["yarn", "dev"]