const integrationTypes = [
  {
    id: 1,
    order: '1',
    name: 'Active Campaign',
    website: 'https://www.activecampaign.com/br/',
    logo: 'https://www.activecampaign.com/site/assets/logo-white.svg',
    active: true,
  },
  {
    id: 2,
    order: '2',
    name: 'LeadLovers',
    website: 'https://www.leadlovers.com/',
    logo: 'https://blob.contato.io/machine-files/all-images/leadlovers-marca.svg',
    active: true,
  },
  {
    id: 3,
    order: '3',
    name: 'eNotas',
    website: 'https://enotas.com.br/',
    logo: 'https://enotas.com.br/wp-content/themes/enotas-4.3/ativos/img/logos/enotas.png?v=2',
    active: true,
    key: 'enotas',
  },
  {
    id: 4,
    order: '4',
    name: 'MailChimp',
    website: 'https://mailchimp.com/pt-br/',
    logo: 'https://cdn.ciroapp.com/wp-content/uploads/2021/05/Mailchimp-logo.png',
    active: true,
    key: 'mailchimp',
  },
  {
    id: 5,
    order: '5',
    name: 'HotzApp',
    website: 'https://hotzapp.me/',
    logo: 'https://hotzapp.me/images/logo.png',
    active: true,
    key: 'hotzapp',
  },
  {
    id: 6,
    order: '6',
    name: 'Webhooks',
    website: 'https://hotzapp.me/',
    logo: 'https://hotzapp.me/images/logo.png',
    active: true,
    key: 'webhooks',
  },
  {
    id: 7,
    order: '7',
    name: 'Voxuy',
    website: 'https://www.voxuy.com/',
    logo: 'https://www.voxuy.com/assets/img/logo-new.svg',
    active: true,
    key: 'voxuy',
  },
  {
    id: 8,
    order: '8',
    name: 'SellFlux',
    website: 'https://sellflux.app',
    logo: 'https://agenciars.com.br/wp-content/uploads/2022/06/Sellflux-img.jpg',
    active: true,
    key: 'sellflux',
  },
  {
    id: 9,
    order: '9',
    name: 'Cademí',
    website: 'https://cademi.com.br',
    logo: 'https://cademi.com.br/wp-content/uploads/2020/06/logo.svg',
    active: true,
    key: 'cademi',
  },
  {
    id: 10,
    order: '10',
    name: 'Bling',
    website: 'https://www.bling.com.br',
    logo: 'https://www.vancecontabil.com.br/wp-content/uploads/2021/06/logo-bling-png-1.png',
    active: true,
    key: 'bling',
  },
  {
    id: 11,
    order: '11',
    name: 'Bling Transporte',
    website: 'https://www.bling.com.br',
    logo: 'https://www.vancecontabil.com.br/wp-content/uploads/2021/06/logo-bling-png-1.png',
    active: true,
    key: 'blingshipping',
  },
  {
    id: 12,
    order: '12',
    name: 'HSDS',
    website: 'https://hsds.io/',
    logo: 'https://hsds.io/wp-content/uploads/2022/04/Co%CC%81pia-de-Co%CC%81pia-de-Co%CC%81pia-de-DS-e1649714245175.png',
    active: true,
    key: 'hsds',
  },
  {
    id: 13,
    order: '13',
    name: 'Invision',
    website: 'https://invisioncommunity.com',
    logo: 'https://play-lh.googleusercontent.com/QrU3CG-wu6vw3NX8zZVVe2wbcfRcscuF9fKKWH2z1tVgjDNiDWxekpTvH2TBeWuUjqY=w240-h480',
    active: true,
    key: 'invision',
  },
  {
    id: 14,
    order: '14',
    name: 'Memberkit',
    website: 'https://memberkit.com.br',
    logo: 'https://static.wixstatic.com/media/07fb26_b3252f9edf4e45fe8d92e77684d73f5f~mv2.png/v1/crop/x_0,y_92,w_300,h_117/fill/w_339,h_132,al_c,lg_1,q_85,enc_auto/member-kit.png',
    active: true,
    key: 'memberkit',
  },
  {
    id: 15,
    order: '15',
    name: 'Notazz',
    website: 'https://notazz.com/',
    logo: 'https://www.negociosemmente.com.br/wp-content/uploads/2022/06/Logos-Ferramentas-e-Cursos-2.png',
    active: true,
    key: 'notazz',
  },
  {
    id: 16,
    order: '16',
    name: 'Bling Transporte V3',
    website: 'https://www.bling.com.br',
    logo: 'https://www.vancecontabil.com.br/wp-content/uploads/2021/06/logo-bling-png-1.png',
    active: true,
    key: 'blingshippingv3',
  },
  {
    id: 17,
    order: '17',
    name: 'Astron Members',
    website: 'https://www.astronmembers.com.br',
    logo: 'https://cdn.eduzzcdn.com/space/upload/c3/0f/c30f31ad92c44414ba8b1456657700be',
    active: true,
    key: 'astronmembers',
  },
  {
    id: 18,
    order: '18',
    name: 'UTMify',
    website: 'https://utmify.com.br',
    logo: 'https://i.ytimg.com/vi/yUAKbakwX0c/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGCwgNih_MA8=&rs=AOn4CLAD8zvdbdVSdb4nx5ayAfs8zrDYHg',
    active: true,
    key: 'utmify',
  },
  {
    id: 19,
    order: '19',
    name: 'Shopify',
    website: 'https://www.shopify.com/br',
    logo: 'https://anyhub.com.br/wp-content/uploads/2023/10/Shopify-Logo.png',
    active: true,
    key: 'shopify',
  },
  {
    id: 20,
    order: '20',
    name: 'Arco',
    website: 'https://hmg-pedidos.capsulbrasil.com.br',
    logo: 'https://capsulbrasil.com.br/assets/img/img-carregamento-do-video.jpg',
    active: true,
    key: 'arco',
  },
  {
    id: 21,
    order: '21',
    name: 'Frenet',
    website: 'Frenet',
    logo: 'https://www.frenet.com.br/wp-content/uploads/2025/01/logo-frenet-bco-10anos-1.png',
    active: true,
    key: 'frenet',
  },
  {
    id: 22,
    order: '22',
    name: 'Tiny',
    website: 'https://tiny.com.br',
    logo: 'https://awakebrasil.com.br/wp-content/uploads/2014/07/tiny-logo-v.png',
    active: true,
    key: 'tiny',
  },
  {
    id: 23,
    order: '23',
    name: 'Zoppy',
    website: 'Zoppy',
    logo: 'https://www.zoppy.com.br/blog/wp-content/uploads/2024/12/Group-39.svg',
    active: true,
    key: 'zoppy',
  },
  {
    id: 24,
    order: '24',
    name: 'Omie',
    website: 'https://www.omie.com.br',
    logo: 'https://www.omie.com.br/wp-content/uploads/2021/03/logo-omie-branco.png',
    active: true,
    key: 'omie',
  },
  {
    id: 25,
    order: '25',
    name: 'Tiktok',
    website: 'https://tiktok.com',
    logo: 'https://logospng.org/wp-content/uploads/tiktok.png',
    active: true,
    key: 'tiktok',
  }
];

export const findIntegrationTypeByKey = (type) => {
  if (!type) throw new Error('type must be provided');
  if (typeof type !== 'string' && typeof type !== 'number')
    throw new Error('type must be string or number');
  const parameter = typeof type === 'string' ? 'key' : 'id';
  const selectedType = integrationTypes.find((s) => s[parameter] === type);
  return selectedType;
};
