const messageParse = (number) => {
  const mensagens = {
    1: 'Tamanho inválido para o ano de expiração',
    2: 'Formato inválido para o ano de expiração',
    3: 'Parâmetro obrigatório de ano de expiração ausente',
    4: 'Tamanho inválido para cvv',
    5: 'Formato inválido para cvv',
    6: 'Tamanho inválido para o código postal',
    7: 'Formato inválido para o código postal',
    8: 'Parâmetro obrigatório para o código postal ausente',
    9: 'Tamanho inválido para complemento',
    10: 'Formato inválido para complemento',
    11: 'Formato inválido para taxa de partida',
    12: 'Tamanho inválido para número do documento',
    13: 'Formato inválido para número do documento',
    14: 'Parâmetro obrigatório para número do documento ausente',
    15: 'Tamanho inválido para código de segurança',
    16: 'Formato inválido para código de segurança',
    17: 'Tamanho inválido para afiliação do distribuidor',
    18: 'Formato inválido para afiliação do distribuidor',
    19: 'Tamanho inválido para xid',
    20: 'Formato inválido para eci',
    21: 'Parâmetro obrigatório para cartão Visa ausente',
    22: 'Parâmetro obrigatório para rua ausente',
    23: 'Formato inválido para rua',
    24: 'Tamanho inválido para afiliação',
    25: 'Formato inválido para afiliação',
    26: 'Parâmetro obrigatório para afiliação ausente',
    27: 'Parâmetro cavv ou eci ausente',
    28: 'Tamanho inválido para código',
    29: 'Formato inválido para código',
    30: 'Parâmetro obrigatório para código ausente',
    31: 'Tamanho inválido para descritor suave',
    32: 'Formato inválido para descritor suave',
    33: 'Formato inválido para mês de expiração',
    34: 'Formato inválido para código',
    35: 'Parâmetro obrigatório para mês de expiração ausente',
    36: 'Tamanho inválido para número do cartão',
    37: 'Formato inválido para número do cartão',
    38: 'Parâmetro obrigatório para número do cartão ausente',
    39: 'Tamanho inválido para referência',
    40: 'Formato inválido para referência',
    41: 'Parâmetro obrigatório para referência ausente',
    42: 'Número do pedido já existe',
    43: 'Tamanho inválido para número',
    44: 'Formato inválido para número',
    45: 'Parâmetro obrigatório para número ausente',
    46: 'Número de parcelas não corresponde à transação de autorização',
    47: 'Formato inválido para origem',
    49: 'O valor da transação excede o autorizado',
    50: 'Formato inválido para número de parcelas',
    51: 'Produto ou serviço desabilitado para este comerciante. Contate a Rede',
    53: 'Transação não permitida para o emissor. Contate a Rede',
    54: 'Parâmetro não permitido para esta transação',
    55: 'Tamanho inválido para nome do titular do cartão',
    56: 'Erro nos dados informados. Tente novamente',
    57: 'Comerciante inválido',
    58: 'Não autorizado. Contate o emissor',
    59: 'Formato inválido para nome do titular do cartão',
    60: 'Tamanho inválido para rua',
    61: 'Formato inválido para assinatura',
    63: 'Não habilitado para este comerciante',
    64: 'Transação não processada. Tente novamente',
    65: 'Token inválido',
    66: 'Tamanho inválido para taxa de partida',
    67: 'Formato inválido para taxa de partida',
    68: 'Parâmetro obrigatório para taxa de partida ausente',
    69: 'Transação não permitida para este produto ou serviço',
    70: 'Tamanho inválido para valor',
    71: 'Formato inválido para valor',
    72: 'Contate o emissor',
    73: 'Parâmetro obrigatório para valor ausente',
    74: 'Falha na comunicação. Tente novamente',
    75: 'Parâmetro de taxa de partida não deve ser enviado para este tipo de transação',
    76: 'Formato inválido para tipo',
    78: 'Transação não existe',
    79: 'Cartão vencido. Transação não pode ser reenviada. Contate o emissor',
    80: 'Não autorizado. Contate o emissor (Fundos insuficientes)',
    82: 'Transação não autorizada para cartão de débito',
    83: 'Não autorizado. Contate o emissor',
    84: 'Não autorizado. Transação não pode ser reenviada. Contate o emissor',
    85: 'Tamanho inválido para complemento',
    86: 'Cartão vencido',
    87: 'Pelo menos um dos seguintes campos deve ser preenchido: tid ou referência',
    88: 'Comerciante não aprovado. Regularize seu website e contate a Rede para voltar a transacionar',
    89: 'Token inválido',
    97: 'Tamanho inválido para tid',
    98: 'Formato inválido para tid',
    132: 'Tamanho inválido para DirectoryServerTransactionId',
    133: 'Valor inválido para ThreedIndicator',
    150: 'Tempo esgotado. Tente novamente',
    151: 'Número de parcelas maior do que o permitido',
    153: 'Número do documento inválido',
    154: 'Formato inválido para embutido',
    155: 'Parâmetro obrigatório para eci ausente',
    156: 'Tamanho inválido para eci',
    157: 'Parâmetro obrigatório para cavv ausente',
    158: 'Tipo não permitido para esta transação',
    159: 'Tamanho inválido para userAgent',
    160: 'Parâmetro obrigatório para urls ausente (tipo)',
    161: 'Formato inválido para urls',
    167: 'JSON de requisição inválido',
    169: 'Tipo de conteúdo inválido',
    171: 'Operação não permitida para esta transação',
    173: 'Autorização expirada',
    176: 'Parâmetro obrigatório para urls ausente (url)',
    899: 'Sem sucesso. Por favor, contate a Rede',
    1018: 'Tamanho inválido para MCC',
    1019: 'Parâmetro MCC obrigatório',
    1020: 'Formato inválido para MCC',
    1021: 'Tamanho inválido para PaymentFacilitatorID',
    1023: 'Formato inválido para PaymentFacilitatorID',
    1030: 'Tamanho inválido para CitySubMerchant',
    1034: 'Tamanho inválido para CountrySubMerchant',
  };

  return (
    mensagens[number] ||
    'Verifique com atencao os dados do seu cartão de crédito'
  );
};

module.exports = {
  messageParse,
};
