module.exports.messages = [
  {
    id: '1000',
    message:
      'Transação não autorizada, oriente o portador a contatar o banco/emissor do cartão',
  },
  {
    id: '1001',
    message:
      'Cartão vencido ou data de vencimento incorreta. Oriente o usuário a contatar o banco/emissor do cartão',
  },
  { id: '1002', message: 'Cartão com suspeita de fraude' },
  {
    id: '1003',
    message: 'Estabelecimento, favor contatar a operadora de cartão',
  },
  {
    id: '1004',
    message:
      'Cartão com restrição. Oriente o usuário a contatar o banco/emissor do cartão',
  },
  {
    id: '1005',
    message: 'Estabelecimento, favor contatar a operadora de cartão',
  },
  {
    id: '1006',
    message: 'O portador do cartão excedeu o número de tentativas de senha',
  },
  {
    id: '1007',
    message:
      'Compra recusada pelo seu Banco. Entre em contato através do telefone ou chat do app do banco e tente novamente após desbloqueio',
  },
  {
    id: '1008',
    message:
      'Compra recusada pelo seu Banco. Entre em contato através do telefone ou chat do app do banco e tente novamente após desbloqueio',
  },
  {
    id: '1009',
    message:
      'Compra recusada pelo seu Banco. Entre em contato através do telefone ou chat do app do banco e tente novamente após desbloqueio',
  },
  { id: '1010', message: 'O valor solicitado para captura não é válido' },
  {
    id: '1011',
    message:
      'Número do cartão inválido. Oriente o usuário a contatar o banco/emissor do cartão',
  },
  { id: '1012', message: 'Senha necessária para efetuar a transação' },
  { id: '1014', message: 'Conta requerida não encontrada' },
  { id: '1016', message: 'Saldo insuficiente' },
  { id: '1017', message: 'Senha incorreta' },
  { id: '1018', message: 'Não há registros deste cartão' },
  {
    id: '1019',
    message:
      'Sistema de prevenção do banco não autorizou a compra. Oriente o usuário a contatar o banco/emissor do cartão',
  },
  { id: '1020', message: 'Transação não permitida para este terminal' },
  { id: '1022', message: 'Transação não autorizada por violação de segurança' },
  { id: '1024', message: 'Transação não autorizada por violação das leis' },
  {
    id: '1025',
    message:
      'Cartão desabilitado. Oriente o usuário a contatar o banco/emissor do cartão',
  },
  { id: '1026', message: 'Senha de bloqueio inválida' },
  { id: '1029', message: 'Cartão com suspeita de falsificação' },
  { id: '1030', message: 'Moeda não suportada pelo emissor' },
  { id: '1031', message: 'Transação não autorizada, com disputa de taxas' },
  { id: '1032', message: 'Cartão bloqueado por perda ou roubo' },
  { id: '1033', message: 'Período para autorização solicitada não aceito' },
  { id: '1034', message: 'Período da autorização expirado' },
  { id: '1035', message: 'Conta encerrada' },
  { id: '1036', message: 'Conta bancária encerrada' },
  { id: '1037', message: 'Conta bancária encerrada' },
  { id: '1038', message: 'Conta bancária encerrada' },
  { id: '1039', message: 'Conta bancária encerrada' },
  { id: '1040', message: 'Cartão inadimplente' },
  { id: '1041', message: 'Conta com status negativo' },
  { id: '1042', message: 'Conta com status negativo' },
  { id: '1043', message: 'Cheque já foi compensado anteriormente' },
  { id: '1044', message: 'Falta de informações no arquivo' },
  { id: '1045', message: 'Código de segurança inválido' },
  { id: '1046', message: 'Valor da transação não encontrado' },
  { id: '1047', message: 'Oriente o usuário a alterar sua senha' },
  { id: '1048', message: 'Nova senha inválida' },
  { id: '1049', message: 'Banco/emissor do cartão inválido' },
  { id: '1050', message: 'Banco/emissor do cartão não operante' },
  { id: '1051', message: 'Fornecedor não encontrado' },
  { id: '1052', message: 'Fornecedor inativo' },
  { id: '1053', message: 'Conta do fornecedor inválida' },
  { id: '1054', message: 'Fornecedor não encontrado' },
  { id: '1055', message: 'Fornecedor inativo' },
  { id: '1056', message: 'Dados do fornecedor inválidos' },
  { id: '1057', message: 'Data de pagamento inválida' },
  { id: '1058', message: 'Informações pessoais não encontradas' },
  { id: '1059', message: 'Há transações em lista de espera' },
  { id: '1060', message: 'Erro ao completar a transação no terminal' },
  {
    id: '1061',
    message: 'Transação não suportada para este banco/emissor do cartão',
  },
  { id: '1062', message: 'Estorno não permitido para esta transação' },
  { id: '1063', message: 'Limite do valor estornado foi excedido' },
  {
    id: '1064',
    message: 'Transação recusada e processada por um terminal offline',
  },
  {
    id: '1065',
    message:
      'Transação recusada pela impossibilidade do terminal processar a transação offline',
  },
  {
    id: '1066',
    message: 'Transação recusada e processada offline após revisão',
  },
  {
    id: '1068',
    message: 'Número do documento de identificação do usuário inválido',
  },
  {
    id: '1069',
    message: 'Número do documento de identificação do usuário inválido',
  },
  {
    id: '1070',
    message: 'Número do documento de identificação do usuário inválido',
  },
  { id: '1071', message: 'Certificado digital expirado' },
  {
    id: '2000',
    message:
      'Compra recusada pelo seu Banco. Entre em contato através do telefone ou chat do app do banco e tente novamente após desbloqueio',
  },
  {
    id: '2001',
    message:
      'Cartão vencido ou data de vencimento incorreta. Oriente o usuário a contatar o banco/emissor do cartão',
  },
  {
    id: '2002',
    message:
      'Compra recusada pelo cartão de crédito. Entre em contato com o seu banco e tente novamente',
  },
  {
    id: '2003',
    message: 'Estabelecimento, favor contatar a operadora de cartão',
  },
  {
    id: '2004',
    message:
      'Cartão com restrição. Oriente o usuário a contatar o banco/emissor do cartão',
  },
  {
    id: '2005',
    message:
      'Estabelecimento, favor contatar a área de risco da operadora de cartão',
  },
  { id: '2006', message: 'O número de tentativas de senha foi excedido' },
  {
    id: '2007',
    message:
      'Sistema de prevenção do banco não autorizou a compra. Oriente o usuário a contatar o banco/emissor do cartão',
  },
  { id: '2008', message: 'Cartão bloqueado por perda ou roubo' },
  { id: '2009', message: 'Cartão bloqueado por perda ou roubo' },
  { id: '2010', message: 'Cartão com suspeita de falsificação' },
  { id: '2011', message: 'Limite diário de saques excedido' },
  { id: '2012', message: 'Valor de saque diário excedido' },
  { id: '5000', message: 'Erro genérico' },
  { id: '5001', message: 'Erro interno' },
  { id: '5002', message: 'Modalidade de pagamento não habilitado' },
  { id: '5003', message: 'Erro interno' },
  { id: '5004', message: 'Erro interno' },
  {
    id: '5005',
    message:
      'O número de parcelas solicitado ultrapassa o máximo permitido para esta loja',
  },
  { id: '5006', message: 'Erro interno' },
  {
    id: '5007',
    message: 'Cartão de débito tentando utilizar produto de crédito',
  },
  { id: '5008', message: 'Erro interno' },
  { id: '5009', message: 'Erro interno' },
  { id: '5010', message: 'Erro interno' },
  { id: '5011', message: 'Erro interno' },
  { id: '5012', message: 'Erro interno' },
  { id: '5013', message: 'Erro interno' },
  { id: '5014', message: 'Erro interno' },
  { id: '5015', message: 'Erro interno' },
  { id: '5016', message: 'O valor solicitado para captura não é válido' },
  { id: '5017', message: 'Erro interno' },
  { id: '5018', message: 'Erro interno' },
  { id: '5019', message: 'Erro interno' },
  { id: '5020', message: 'Erro interno' },
  { id: '5021', message: 'Erro interno' },
  { id: '5022', message: 'Erro interno' },
  { id: '5023', message: 'Erro interno' },
  { id: '5024', message: 'Erro interno' },
  {
    id: '5025',
    message: 'Código de segurança (CVV) do cartão não foi enviado',
  },
  { id: '5026', message: 'Erro interno' },
  { id: '5027', message: 'Erro interno' },
  { id: '5028', message: 'Erro interno' },
  { id: '5029', message: 'Erro interno' },
  { id: '5030', message: 'Erro interno' },
  { id: '5031', message: 'Erro interno' },
  { id: '5032', message: 'Erro interno' },
  { id: '5033', message: 'Erro interno' },
  { id: '5034', message: 'Campo obrigatório ano ausente' },
  { id: '5035', message: 'Erro interno' },
  { id: '5036', message: 'Erro interno' },
  { id: '5037', message: 'Erro interno' },
  { id: '5038', message: 'Erro interno' },
  { id: '5039', message: 'Erro interno' },
  { id: '5040', message: 'Erro interno' },
  { id: '5041', message: 'Erro interno' },
  { id: '5042', message: 'Erro interno' },
  { id: '5043', message: 'Erro interno' },
  { id: '5044', message: 'Erro interno' },
  { id: '5045', message: 'Erro interno' },
  { id: '5046', message: 'Valor do campo Mês inválido' },
  { id: '5047', message: 'Campo Mês ausente' },
  {
    id: '5048',
    message: 'A quantidade de parcelas não corresponde à transação autorizada',
  },
  { id: '5049', message: 'Erro interno' },
  { id: '5050', message: 'Erro interno' },
  { id: '5051', message: 'O valor da transação excede o autorizado' },
  { id: '5052', message: 'Erro interno' },
  { id: '5053', message: 'Erro interno' },
  { id: '5054', message: 'Erro interno' },
  { id: '5055', message: 'Erro interno' },
  { id: '5056', message: 'Erro interno' },
  { id: '5057', message: 'Erro interno' },
  { id: '5058', message: 'Erro interno' },
  { id: '5059', message: 'Erro interno' },
  { id: '5060', message: 'Erro interno' },
  { id: '5061', message: 'Campo Senha ausente' },
  { id: '5062', message: 'Erro interno' },
  { id: '5063', message: 'Erro interno' },
  { id: '5064', message: 'Erro interno' },
  { id: '5065', message: 'Erro interno' },
  { id: '5066', message: 'Erro interno' },
  { id: '5067', message: 'Erro interno' },
  { id: '5068', message: 'Erro interno' },
  { id: '5069', message: 'Erro interno' },
  { id: '5070', message: 'Erro interno' },
  { id: '5071', message: 'Erro interno' },
  { id: '5072', message: 'Erro interno' },
  { id: '5073', message: 'Erro interno' },
  { id: '5074', message: 'Erro interno' },
  { id: '5075', message: 'Erro interno' },
  { id: '5076', message: 'Erro interno' },
  { id: '5077', message: 'Erro interno' },
  { id: '5078', message: 'Erro interno' },
  { id: '5079', message: 'Erro interno' },
  { id: '5080', message: 'Erro interno' },
  { id: '5081', message: 'Erro interno' },
  { id: '5082', message: 'Erro interno' },
  { id: '5083', message: 'Erro interno' },
  { id: '5084', message: 'Erro interno' },
  { id: '5085', message: 'Erro interno' },
  { id: '5086', message: 'Cartão poupança inválido' },
  { id: '5087', message: 'Transação não autorizada. Limite diário excedido.' },
  { id: '5088', message: 'Transação não autorizada AmEx.' },
  { id: '5089', message: 'Erro interno' },
  { id: '5090', message: 'Erro interno' },
  {
    id: '5091',
    message:
      'Transação não permitida. Valor da parcela inferior ao mínimo permitido.',
  },
  { id: '5092', message: 'O valor solicitado para captura não é válido' },
  {
    id: '5093',
    message:
      'Transação não autorizada, oriente o portador a contatar o banco/emissor do cartão',
  },
  { id: '5094', message: 'Venda com parcelamento não habilitado' },
  { id: '5095', message: 'Erro interno' },
  { id: '5096', message: 'Erro interno' },
  { id: '5097', message: 'Erro interno' },
  { id: '9100', message: 'Erro nos elementos do arquivo enviado' },
  { id: '9102', message: 'Transação inválida. Contate a operadora de cartão' },
  { id: '9103', message: 'Retente a transação' },
  { id: '9105', message: 'Operadora de cartão não suportada pela conexão' },
  { id: '9106', message: 'Transição em processo' },
  {
    id: '9107',
    message: 'O banco/emissor do cartão ou a conexão parece estar offline',
  },
  { id: '9108', message: 'Destino da transação não encontrado' },
  { id: '9109', message: 'Erro no sistema do banco ou operadora de cartão' },
  { id: '9110', message: 'Banco/emissor do cartão parece estar offline' },
  { id: '9111', message: 'Time out. Banco/emissor do cartão não respondeu' },
  { id: '9112', message: 'Banco/emissor do cartão indisponível' },
  { id: '9113', message: 'Transmissão duplicada' },
  { id: '9114', message: 'Não foi possível localizar a transação original' },
  { id: '9115', message: 'Erro na reconciliação' },
  { id: '9116', message: 'MAC incorreto' },
  { id: '9117', message: 'Erro ao sincronizar a chave do MAC' },
  { id: '9118', message: 'Nenhuma chave de comunicação disponível' },
  { id: '9119', message: 'Erro na sincronização da chave de encriptação' },
  { id: '9120', message: 'Erro de software/hardware. Tente novamente' },
  { id: '9121', message: 'Erro de software/hardware' },
  { id: '9122', message: 'Número da mensagem fora de sequência' },
  { id: '9123', message: 'Requisição em processo' },
  { id: '9124', message: 'Código de segurança inválido' },
  { id: '9125', message: 'Erro no banco de dados' },
  { id: '9128', message: 'Formato dos dados de fornecedor inválido' },
  { id: '9132', message: 'Erro na recorrência de dados' },
  { id: '9133', message: 'Atualização não permitida' },
  { id: '9200', message: 'Entre em contato com o suporte' },
  { id: '9350', message: 'O acordo comercial foi violado' },
  { id: '9999', message: 'Erro genérico' },
  { id: 'IMSG', message: 'Erro interno' },
  { id: 'UNPR', message: 'Erro interno' },
];
