const MAX_ATTEMPTS = 8;
const ATTEMPT_WINDOW = 24 * 60 * 60 * 30;

const MAX_ATTEMPTS_EMAIL = 8;
const ATTEMPT_WINDOW_EMAIL = 24 * 60 * 60 * 30;

const MAX_ATTEMPTS_IP = 8;
const ATTEMPT_WINDOW_IP = 24 * 60 * 60 * 30;

const MAX_ATTEMPTS_VISITOR = 10;
const ATTEMPT_WINDOW_VISITOR = 24 * 60 * 60 * 30;

const MAX_ATTEMPTS_SESSION_ID = 8;
const ATTEMPT_WINDOW_SESSION_ID = 24 * 60 * 60 * 30;

const MAX_ATTEMPTS_NAME_OFFER = 8;
const ATTEMPT_WINDOW_NAME_OFFER = 24 * 60 * 60 * 30;

module.exports = {
  MAX_ATTEMPTS,
  ATTEMPT_WINDOW,
  MAX_ATTEMPTS_EMAIL,
  ATTEMPT_WINDOW_EMAIL,
  MAX_ATTEMPTS_IP,
  ATTEMPT_WINDOW_IP,
  MAX_ATTEMPTS_VISITOR,
  ATTEMPT_WINDOW_VISITOR,
  MAX_ATTEMPTS_SESSION_ID,
  ATTEMPT_WINDOW_SESSION_ID,
  MAX_ATTEMPTS_NAME_OFFER,
  ATTEMPT_WINDOW_NAME_OFFER,
};
