module.exports = {
  DATABASE_DATE: 'YYYY-MM-DD HH:mm:ss',
  FRONTEND_DATE: 'DD/MM/YYYY - HH:mm:ss',
  DATABASE_DATE_WITHOUT_TIME: 'YYYY-MM-DD',
  EXPIRATION_CARD_DATE: 'MM/YYYY',
  FRONTEND_DATE_WITHOUT_TIME: 'DD/MM/YYYY',
  BILLET_DUE_DATE: 'YYYY-MM-DD',
};
