export const EVENT_DESCRIPTIONS = {
  checkout_page_view: 'Checkout page view',
  checkout_session_started: 'Checkout session started',
  checkout_identification_started: 'User started identification',
  checkout_identification_filled: 'Identification fields filled',
  checkout_identification_error: 'Identification validation error',
  checkout_identification_completed: 'Identification completed',
  checkout_address_started: 'User started address',
  checkout_address_filled: 'Address fields filled',
  checkout_address_error: 'Address validation error',
  checkout_shipping_method_selected: 'Shipping method selected',
  checkout_address_completed: 'Address completed',
  checkout_step_viewed: 'Checkout step viewed',
  checkout_step_advanced: 'Checkout step advanced',
  checkout_step_back: 'Checkout step back',
  checkout_payment_method_selected: 'Payment method selected',
  checkout_payment_data_started: 'Payment data entry started',
  checkout_payment_data_error: 'Payment data validation error',
  checkout_coupon_applied: 'Coupon applied',
  checkout_coupon_error: 'Coupon error',
  checkout_order_bump_viewed: 'Order bump viewed',
  checkout_order_bump_accepted: 'Order bump accepted',
  checkout_order_bump_declined: 'Order bump declined',
  checkout_submit_clicked: 'Checkout submit clicked',
  checkout_payment_success: 'Checkout payment success',
  checkout_conversion_success: 'Checkout conversion success',
  checkout_payment_error: 'Checkout payment error',
};
