import {
  Home,
  Users,
  User,
  Archive,
  DollarSign,
  BarChart,
  Eye,
  ShoppingCart,
  List,
  Percent,
  UserCheck,
  Upload,
  ShieldOff,
  Lock,
  Briefcase,
  Gift,
  Bell,
  Award,
  Video,
  Settings,
  CreditCard,
  Activity,
  FileText,
  BookOpen
} from 'react-feather';

const routes = [
  {
    id: 'home',
    title: 'Home',
    icon: <Home size={20} />,
    navLink: '/home',
    action: 'manage',
    resource: 'Home',
  },
  {
    id: 'financeiro',
    title: 'Financeiro',
    icon: <BarChart size={20} />,
    navLink: '/reports',
    action: 'manage',
    resource: 'Reports',
  },
  {
    id: 'pagarme',
    title: 'Pagarme',
    icon: <UserCheck size={20} />,
    navLink: '/pagarme',
    action: 'manage',
    resource: 'Pagarme',
  },
  {
    id: 'sales',
    title: 'Vendas',
    icon: <DollarSign size={20} />,
    navLink: '/sales',
    action: 'manage',
    resource: 'Sales',
  },
  // {
  //   id: 'kycPage',
  //   title: 'KYC',
  //   icon: <Award size={20} />,
  //   navLink: '/kyc',
  //   action: 'manage',
  //   resource: 'KYC',
  // },
  {
    id: 'studentsPage',
    title: 'Clientes',
    icon: <Users size={20} />,
    navLink: '/students',
    action: 'manage',
    resource: 'Students',
  },
  {
    id: 'producersPage',
    title: 'Produtores',
    icon: <User size={20} />,
    navLink: '/producers',
    action: 'manage',
    resource: 'Producers',
  },
  {
    id: 'creatorsPage',
    title: 'Creators',
    icon: <Video size={20} />,
    navLink: '/creators',
    action: 'manage',
    resource: 'Creators',
  },
  {
    id: 'onboardingPage',
    title: 'Onboarding',
    icon: <User size={20} />,
    navLink: '/onboarding',
    action: 'manage',
    resource: 'Onboarding',
  },
  {
    id: 'productsPage',
    title: 'Produtos',
    icon: <Archive size={20} />,
    navLink: '/products',
    action: 'manage',
    resource: 'Products',
  },
  // {
  //   id: 'eventsPage',
  //   title: 'Conversões',
  //   icon: <Percent size={20} />,
  //   navLink: '/events',
  //   action: 'manage',
  //   resource: 'Events',
  // },
  {
    id: 'market-pending',
    title: 'Mercado(pendentes)',
    icon: <ShoppingCart size={20} />,
    navLink: '/market',
    action: 'manage',
    resource: 'Market',
  },
  {
    id: 'checkout-analytics',
    title: 'Analytics Checkout',
    icon: <BarChart size={20} />,
    navLink: '/checkout-analytics',
    action: 'manage',
    resource: 'CheckoutAnalytics',
  },
  //{
  //id: 'market-banner',
  //title: 'Mercado (banner)',
  //icon: <Image size={20} />,
  //navLink: '/market-banner',
  //action: 'manage',
  //resource: 'MarketBanner',
  //},
  {
    id: 'logs',
    title: 'Logs',
    icon: <Eye size={20} />,
    navLink: '/logs',
    action: 'manage',
    resource: 'Logs',
  },
  {
    id: 'cloudwatch-logs',
    title: 'Logs CloudWatch',
    icon: <Activity size={20} />,
    navLink: '/cloudwatch-logs',
    action: 'manage',
    resource: 'CloudWatchLogs',
  },
  {
    id: 'withdrawals',
    title: 'Saques manuais',
    icon: <Upload size={20} />,
    navLink: '/saques',
    action: 'manage',
    resource: 'Withdrawals',
  },
  {
    id: 'blacklist',
    title: 'Antifraude',
    icon: <Lock size={20} />,
    navLink: '/blacklist',
    action: 'manage',
    resource: 'Blacklist',
  },
  {
    id: 'blocks',
    title: 'Restrições',
    icon: <ShieldOff size={20} />,
    navLink: '/blocks',
    action: 'manage',
    resource: 'Blocks',
  },
  {
    id: 'blocklist',
    title: 'Lista de Bloqueios',
    icon: <List size={20} />,
    navLink: '/blocklist',
    action: 'manage',
    resource: 'Blocklist',
  },
  {
    id: 'sale-ip',
    title: 'Vendas por IP',
    icon: <DollarSign size={20} />,
    navLink: '/sale-ip',
    action: 'manage',
    resource: 'SaleIP',
  },
  {
    id: 'commercial',
    title: 'Comercial',
    icon: <Briefcase size={20} />,
    navLink: '/commercial',
    action: 'manage',
    resource: 'Commercial',
  },
  {
    id: 'client-wallet',
    title: 'Carteira de Clientes',
    icon: <CreditCard size={20} />,
    navLink: '/client-wallet',
    action: 'manage',
    resource: 'ClientWallet',
  },
  {
    id: 'change-bank-account',
    title: 'Alteração de Conta Bancária',
    icon: <CreditCard size={20} />,
    navLink: '/change-bank-account',
    action: 'manage',
    resource: 'ChangeBankAccount',
  },
  {
    id: 'indique-ganhe',
    title: 'Indique e Ganhe',
    icon: <Gift size={20} />,
    navLink: '/indique-ganhe',
    action: 'manage',
    resource: 'IndiqueGanhe',
  },
  {
    id: 'notifications',
    title: 'Notificações',
    icon: <Bell size={20} />,
    navLink: '/notifications',
    action: 'manage',
    resource: 'Notifications',
  },
  {
    id: 'awards',
    title: 'Premiações',
    icon: <Award size={20} />,
    navLink: '/awards',
    action: 'manage',
    resource: 'Awards',
  },
  {
    id: 'access_management',
    title: 'Gerenciamento de Acessos',
    icon: <Settings size={20} />,
    navLink: '/admin/access',
    action: 'manage',
    resource: 'AccessManagement',
  },
  {
    id: 'forms-editor',
    title: 'Editor de Formulários',
    icon: <FileText size={20} />,
    navLink: '/forms-editor',
    action: 'manage',
    resource: 'FormsEditor',
  },
  {
    id: 'notes',
    title: 'Notas',
    icon: <BookOpen size={20} />,
    navLink: '/notes',
    action: 'manage',
    resource: 'Notes',
  },
];

export default routes;