FROM node:22-alpine

ENV TZ="America/Sao_Paulo"
WORKDIR /usr/app

RUN apk add --no-cache python3 make g++ bash

COPY package*.json yarn.lock ./
RUN corepack enable && corepack prepare yarn@1.22.22 --activate
RUN yarn install --frozen-lockfile

COPY . .

EXPOSE 5001 9229

CMD ["yarn", "dev:debug"]