const fees = [
  {
    id: 1,
    method: 'CARD',
    brand: 'visa',
    installments: 1,
    psp_variable_cost: 2.45,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 2,
    method: 'CARD',
    brand: 'visa',
    installments: 2,
    psp_variable_cost: 3.16,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 3,
    method: 'CARD',
    brand: 'visa',
    installments: 3,
    psp_variable_cost: 3.89,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 4,
    method: 'CARD',
    brand: 'visa',
    installments: 4,
    psp_variable_cost: 4.62,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 5,
    method: 'CARD',
    brand: 'visa',
    installments: 5,
    psp_variable_cost: 5.35,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 6,
    method: 'CARD',
    brand: 'visa',
    installments: 6,
    psp_variable_cost: 6.08,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 7,
    method: 'CARD',
    brand: 'visa',
    installments: 7,
    psp_variable_cost: 7.01,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 8,
    method: 'CARD',
    brand: 'visa',
    installments: 8,
    psp_variable_cost: 7.74,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 9,
    method: 'CARD',
    brand: 'visa',
    installments: 9,
    psp_variable_cost: 8.47,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 10,
    method: 'CARD',
    brand: 'visa',
    installments: 10,
    psp_variable_cost: 9.2,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 11,
    method: 'CARD',
    brand: 'visa',
    installments: 11,
    psp_variable_cost: 9.93,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 12,
    method: 'CARD',
    brand: 'visa',
    installments: 12,
    psp_variable_cost: 10.66,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 13,
    method: 'CARD',
    brand: 'master',
    installments: 1,
    psp_variable_cost: 2.45,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 14,
    method: 'CARD',
    brand: 'master',
    installments: 2,
    psp_variable_cost: 3.16,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 15,
    method: 'CARD',
    brand: 'master',
    installments: 3,
    psp_variable_cost: 3.89,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 16,
    method: 'CARD',
    brand: 'master',
    installments: 4,
    psp_variable_cost: 4.62,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 17,
    method: 'CARD',
    brand: 'master',
    installments: 5,
    psp_variable_cost: 5.35,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 18,
    method: 'CARD',
    brand: 'master',
    installments: 6,
    psp_variable_cost: 6.08,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 19,
    method: 'CARD',
    brand: 'master',
    installments: 7,
    psp_variable_cost: 7.01,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 20,
    method: 'CARD',
    brand: 'master',
    installments: 8,
    psp_variable_cost: 7.74,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 21,
    method: 'CARD',
    brand: 'master',
    installments: 9,
    psp_variable_cost: 8.47,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 22,
    method: 'CARD',
    brand: 'master',
    installments: 10,
    psp_variable_cost: 9.2,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 23,
    method: 'CARD',
    brand: 'master',
    installments: 11,
    psp_variable_cost: 9.93,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 24,
    method: 'CARD',
    brand: 'master',
    installments: 12,
    psp_variable_cost: 10.66,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 25,
    method: 'CARD',
    brand: 'amex',
    installments: 1,
    psp_variable_cost: 3.56,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 26,
    method: 'CARD',
    brand: 'amex',
    installments: 2,
    psp_variable_cost: 4.24,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 27,
    method: 'CARD',
    brand: 'amex',
    installments: 3,
    psp_variable_cost: 4.97,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 28,
    method: 'CARD',
    brand: 'amex',
    installments: 4,
    psp_variable_cost: 5.7,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 29,
    method: 'CARD',
    brand: 'amex',
    installments: 5,
    psp_variable_cost: 6.43,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 30,
    method: 'CARD',
    brand: 'amex',
    installments: 6,
    psp_variable_cost: 7.16,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 31,
    method: 'CARD',
    brand: 'amex',
    installments: 7,
    psp_variable_cost: 8.06,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 32,
    method: 'CARD',
    brand: 'amex',
    installments: 8,
    psp_variable_cost: 8.79,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 33,
    method: 'CARD',
    brand: 'amex',
    installments: 9,
    psp_variable_cost: 9.52,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 34,
    method: 'CARD',
    brand: 'amex',
    installments: 10,
    psp_variable_cost: 10.25,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 35,
    method: 'CARD',
    brand: 'amex',
    installments: 11,
    psp_variable_cost: 10.98,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 36,
    method: 'CARD',
    brand: 'amex',
    installments: 12,
    psp_variable_cost: 11.71,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 37,
    method: 'CARD',
    brand: 'elo',
    installments: 1,
    psp_variable_cost: 3.38,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 38,
    method: 'CARD',
    brand: 'elo',
    installments: 2,
    psp_variable_cost: 4.44,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 39,
    method: 'CARD',
    brand: 'elo',
    installments: 3,
    psp_variable_cost: 5.17,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 40,
    method: 'CARD',
    brand: 'elo',
    installments: 4,
    psp_variable_cost: 5.9,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 41,
    method: 'CARD',
    brand: 'elo',
    installments: 5,
    psp_variable_cost: 6.63,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 42,
    method: 'CARD',
    brand: 'elo',
    installments: 6,
    psp_variable_cost: 7.36,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 43,
    method: 'CARD',
    brand: 'elo',
    installments: 7,
    psp_variable_cost: 8.56,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 44,
    method: 'CARD',
    brand: 'elo',
    installments: 8,
    psp_variable_cost: 9.29,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 45,
    method: 'CARD',
    brand: 'elo',
    installments: 9,
    psp_variable_cost: 10.02,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 46,
    method: 'CARD',
    brand: 'elo',
    installments: 10,
    psp_variable_cost: 10.75,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 47,
    method: 'CARD',
    brand: 'elo',
    installments: 11,
    psp_variable_cost: 11.48,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 48,
    method: 'CARD',
    brand: 'diners',
    installments: 1,
    psp_variable_cost: 2.45,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 49,
    method: 'CARD',
    brand: 'diners',
    installments: 2,
    psp_variable_cost: 3.16,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 50,
    method: 'CARD',
    brand: 'diners',
    installments: 3,
    psp_variable_cost: 3.89,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 51,
    method: 'CARD',
    brand: 'diners',
    installments: 4,
    psp_variable_cost: 4.62,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 52,
    method: 'CARD',
    brand: 'diners',
    installments: 5,
    psp_variable_cost: 5.35,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 53,
    method: 'CARD',
    brand: 'diners',
    installments: 6,
    psp_variable_cost: 6.08,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 54,
    method: 'CARD',
    brand: 'diners',
    installments: 7,
    psp_variable_cost: 7.01,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 55,
    method: 'CARD',
    brand: 'diners',
    installments: 8,
    psp_variable_cost: 7.74,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 56,
    method: 'CARD',
    brand: 'diners',
    installments: 9,
    psp_variable_cost: 8.47,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 57,
    method: 'CARD',
    brand: 'diners',
    installments: 10,
    psp_variable_cost: 9.2,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 58,
    method: 'CARD',
    brand: 'diners',
    installments: 11,
    psp_variable_cost: 9.93,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 59,
    method: 'CARD',
    brand: 'diners',
    installments: 12,
    psp_variable_cost: 10.66,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 60,
    method: 'CARD',
    brand: 'hiper',
    installments: 1,
    psp_variable_cost: 2.85,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 61,
    method: 'CARD',
    brand: 'hiper',
    installments: 2,
    psp_variable_cost: 3.96,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 62,
    method: 'CARD',
    brand: 'hiper',
    installments: 3,
    psp_variable_cost: 4.69,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 63,
    method: 'CARD',
    brand: 'hiper',
    installments: 4,
    psp_variable_cost: 5.42,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 64,
    method: 'CARD',
    brand: 'hiper',
    installments: 5,
    psp_variable_cost: 6.15,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 65,
    method: 'CARD',
    brand: 'hiper',
    installments: 6,
    psp_variable_cost: 6.88,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 66,
    method: 'CARD',
    brand: 'hiper',
    installments: 7,
    psp_variable_cost: 7.81,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 67,
    method: 'CARD',
    brand: 'hiper',
    installments: 8,
    psp_variable_cost: 8.54,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 68,
    method: 'CARD',
    brand: 'hiper',
    installments: 9,
    psp_variable_cost: 9.27,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 69,
    method: 'CARD',
    brand: 'hiper',
    installments: 10,
    psp_variable_cost: 10.0,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 70,
    method: 'CARD',
    brand: 'hiper',
    installments: 11,
    psp_variable_cost: 10.73,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 71,
    method: 'CARD',
    brand: 'hiper',
    installments: 12,
    psp_variable_cost: 11.46,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 72,
    method: 'BILLET',
    brand: null,
    installments: 1,
    psp_variable_cost: 0.0,
    psp_fixed_cost: 1.49,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 73,
    method: 'PIX',
    brand: null,
    installments: 1,
    psp_variable_cost: 1.0,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 74,
    method: 'WITHDRAWAL_PIX',
    brand: null,
    installments: 1,
    psp_variable_cost: 0.0,
    psp_fixed_cost: 0.5,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 75,
    method: 'WITHDRAWAL_TED',
    brand: null,
    installments: 1,
    psp_variable_cost: 0.0,
    psp_fixed_cost: 2.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 76,
    method: 'REFUND_PIX',
    brand: null,
    installments: 1,
    psp_variable_cost: 0.0,
    psp_fixed_cost: 0.5,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 77,
    method: 'REFUND_BILLET',
    brand: null,
    installments: 1,
    psp_variable_cost: 0.0,
    psp_fixed_cost: 2.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 78,
    method: 'REFUND_CARD',
    brand: null,
    installments: 1,
    psp_variable_cost: 0.0,
    psp_fixed_cost: 0.0,
    additional_variable_cost: 0.0,
    additional_fixed_cost: 0.0,
    created_at: null,
    updated_at: null,
  },
];

module.exports = class CostCentralMemoryRepository {
  static async find() {
    return new Promise((resolve) => {
      resolve(fees);
    });
  }

  static async findByMethod(method) {
    return new Promise((resolve) => {
      resolve(fees.find((f) => f.method === method));
    });
  }
};
